esphome:
  name: dimmer-test
  friendly_name: dimmer-test

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: "HB03mOi4f3uYLyeZnBScaJI8RiwHop3ADu+Po71/9t0="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

logger:
    baud_rate: 0

uart:
    tx_pin: 1
    rx_pin: 3
    baud_rate: 115200

sensor:
  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${device_name} temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: 70
        then:
          - logger.log: "Switch turned off because temperature exceeded ${max_temp}°C"
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Switch turned off because temperature exceeded ${max_temp}°C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

light:
    - platform: shelly_dimmer
      name: Shelly Dimmer 2 Light
      id: thislight
      power:
        name: Shelly Dimmer 2 Light Power
      voltage:
        name: Shelly Dimmer 2 Light Voltage
      current:
        name: Shelly Dimmer 2 Light Current
      max_brightness: 750
      min_brightness: 0
      warmup_brightness: 250
      firmware:
        version: "51.6"
        update: false
      restore_mode: RESTORE_DEFAULT_OFF