esphome:
  name: lamp-switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ParkisSSID
  password: !secret ParkisPassword
  
  ap:
    ssid: "LampSwitch"
    password: !secret AccessPointPassword

  manual_ip:
    static_ip: !secret ip_lamp_switch
    gateway: 192.168.1.1
    subnet: 255.255.255.0

captive_portal:

api:
  encryption:
    key: HJrevqiIOwyvZ5iFuHDl6ukkhgZ12uGrPYO0Po35i94=

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_click:
      if:
        condition:
          api.connected:
        then:
          - switch.turn_on: relay
          - homeassistant.event:
              event: esphome.lamp_press
              data:
                message: Lamp Switch Pressed
        else:
          switch.toggle: relay
    on_double_click:
      homeassistant.event:
        event: esphome.lamp_doublepress
        data:
          message: Lamp Switch Double Pressed
    on_multi_click:
      timing:
        - ON for at least 0.3s
      then:
        homeassistant.event:
          event: esphome.lamp_hold
          data:
            message: Lamp Switch Held
    on_release:
      homeassistant.event:
        event: esphome.lamp_release
        data:
          message: Lamp Switch Released
          
switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF