substitutions:
  device_name: lamp_theo
  esphome_name: lamp-theo
  friendly_name: Lamp Theo
  hotspot_ssid: Lamp Theo

esphome:
  name: ${esphome_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  reboot_timeout: 0s
  networks:
    - ssid: !secret ParkisSSID
      password: !secret ParkisPassword
  manual_ip:
    static_ip: !secret ip_lamp_theo
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  
  ap:
    ssid: ${hotspot_ssid}
    password: !secret AccessPointPassword

captive_portal:

api:
  reboot_timeout: 0s

logger:

ota:

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
    frequency: 900Hz
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
    frequency: 900Hz
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
    frequency: 900Hz
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO5
    frequency: 800Hz

light:
  - platform: rgbw
    name: ${friendly_name}
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    color_interlock: true
    restore_mode: ALWAYS_ON
    gamma_correct: 1.5