esphome:
  name: test

esp8266:
  board: esp01_1m

# Enable logging
logger:

ota:
  password: "94c55380fd609e2726563c737140962e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  
  manual_ip:
    static_ip: !secret ip_lamp_switch_zoey
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    