esphome:
  name: toggle-test
  friendly_name: toggle-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8VElpVQAaDIioUioD9ZHOYbDEmtP57sTuRiUcndQ5Ic="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

binary_sensor:
  - platform: homeassistant
    name: "LED"
    internal: false
    entity_id: input_boolean.auto_garage_door
    on_press:
      then:
        - switch.turn_on: led
    on_release:
      then:
        - switch.turn_off: led
  - platform: gpio
    name: "Switch"
    pin: GPIO4
    on_press:
      then:
        - homeassistant.service:
            service: homeassistant.toggle
            data:
              entity: input_boolean.auto_garage_door
    filters:
      - delayed_on_off: 20ms

output:
  - platform: gpio
    id: "led_output"
    pin: GPIO26

switch:
  - platform: output
    id: "led"
    output: "led_output"