esphome:
  name: toggle-test
  friendly_name: toggle-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8VElpVQAaDIioUioD9ZHOYbDEmtP57sTuRiUcndQ5Ic="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

binary_sensor:
  - platform: homeassistant
    id: auto_garage
    name: "Auto Garage"
    internal: false
    entity_id: binary_sensor.reed_switch
    publish_initial_state: true
    on_state:
      then:
        if:
          condition: 
            binary_sensor.is_on: auto_garage
          then:
            - switch.turn_off: led
          else:
            - switch.turn_on: led
  - platform: gpio
    name: "Switch"
    pin: GPIO4
    on_click:
      - min_length: 5ms
        max_length: 200ms
        then:
          - homeassistant.service:
              service: cover.toggle
              data:
                entity_id: cover.garage_door
      - min_length: 250ms
        max_length: 5s
        then:
          if:
            condition:
              binary_sensor.is_on: auto_garage
            then:
              - homeassistant.service:
                  service: input_boolean.turn_off
                  data:
                    entity_id: input_boolean.auto_garage_door
              - homeassistant.service:
                  service: cover.open_cover
                  data:
                    entity_id: cover.garage_door


output:
  - platform: gpio
    id: "led_output"
    pin: GPIO26

switch:
  - platform: output
    id: "led"
    output: "led_output"